project:
  type: website
  output-dir: docs

website:
  title: "Welcome!"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - papers.qmd
      - cv.qmd

format:
  html:
    theme: 
      light: lumen
      dark: cyborg
    css: styles.css
    toc: true



