project:
  type: website
  output-dir: docs

website:
  title: "Welcome!"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - papers.qmd
      - cv.qmd
  cookie-consent:
    type: express
    style: simple
    palette: dark



format:
  html:
    theme: 
      light: lumen
      dark: cyborg
    css: styles.css
    toc: true



