---
title: "Curriculum Vitae"
---

**René Larisch** \
Blücherstraße 19 \
09126 Chemnitz \
renelarischif@gmail.com \
rene.larisch@informatik.tu-chemnitz.de \


+---------------------------------------------------------------------+-------------------------+
| Work Experience                                                     |                         |
+:====================================================================+========================:+
| Scientific Researcher                                               |     since 06/2025       |
| Professorshipof Artificial Intelligence                             |                         |
| University of Technology Chemnitz                                   |                         |
| in _Therabox_                                                       |                         |
+---------------------------------------------------------------------+-------------------------+
| Scientific Researcher                                               |   10/2024 - 05/2025     |
| Professorshipof Artificial Intelligence                             |                         |
| University of Technology Chemnitz                                   |                         |
| in _Counterfactual Assessment and Valuation_                        |                         |
| _for Awareness Architecture (CAVAA)_                                |                         |
+---------------------------------------------------------------------+-------------------------+
| Scientific Researcher                                               |   09/2020 - 09/2024     |
| Professorshipof Artificial Intelligence                             |                         |
| University of Technology Chemnitz                                   |                         |
| in _Wissensbasierte Anomalieerkennung mittels Künstlicher_          |                         |
| _Intelligenz in Kritischen Infrastrukturen(WAIKIKI)_                |                         |
+---------------------------------------------------------------------+-------------------------+


+---------------------------------------------------------------------+-------------------------+
| Eductation                                                          |                         |
+:====================================================================+========================:+
| PhD at the Professorship                                            |    10/2017 - 03/2025    |
| of Artificial Intelligence                                          |                         |
| University of Technology Chemnitz                                   |                         |
| Title: _The effects of inhibitory plasticity                        |                         |
| and the emerging network dynamics on processing visual information_ |                         |
+---------------------------------------------------------------------+-------------------------+
| Diploma in computer science                                         |  2008 - 2016            |
| University of Technology Chemnitz                                   |                         |
+---------------------------------------------------------------------+-------------------------+


+------------------------------------------+---------------------+
| Teaching Experience                      |                     |
+:=========================================+====================:+
|  - Machine Learning                      | winter semster 17\  |
|  - Machine Learning                      | winter semster 18   |
+------------------------------------------+---------------------+


+------------------------------------------+----------------------+
| Scholarshipts/Grant                      |                      |
+:=========================================+=====================:+
|Grant: _Landesinnovationspromotion_       | 10.2017 - 09.2020    |
|Founded by the European Social Fund(ESF)  |                      |
|and the Free State of Saxony              |                      |
+------------------------------------------+----------------------+
| Travelgrant for a conference application |  10.2018             |
| Founded by **DAAD** and **InProTUC**     |                      |
+------------------------------------------+----------------------+

+------------------------------------------+----------------------+
| Skills                                   |                      |
+:=========================================+=====================:+
| - Programming languages: Python, C++     |                      |
+------------------------------------------+----------------------+
| - Machine learning frameworks:           |                      |
|   Tensorflow, PyTorch, scikit-learn      |                      |
+------------------------------------------+----------------------+
