---
title: "Exploring the Role of Feedback Inhibition for the Robustness Against Corruptions on Event-Based Data"
description: 'Contribution to the ICANN 2023 conference.'
date: 2023-09-22
---

### Abstract

In event-based vision, visual information is encoded by sequential events in space and time, similar to the human visual system, where the retina emits spikes. Thus, spiking neural networks are to be preferred for processing event-based input streams. As for classical deep learning networks, spiking neural networks must be robust against different corruption or perturbations in the input data. However, corruption in event-based data has received little attention so far. According to previous studies, biologically motivated neural networks, consisting of lateral inhibition to implement a competition mechanism between the neurons, show an increase in the robustness against loss of information of input data. We here analyze the influence of inhibitory feedback on the robustness against four different types of corruption on an event-based data set. We demonstrate how a 1 : 1 ratio between feed-forward excitation and feedback inhibition increases the robustness against the loss of events, as well as against additional noisy events. Interestingly, our results show that strong feedback inhibition is a disadvantage if events in the input stream are shifted in space or in time. 

This work was published in Artificial Neural Networks and Machine Learning - ICANN 2023. Lecture Notes in Computer Science, vol 14261. Springer, Cham..

Please cite this work as:

'Larisch, R., Berger, L., Hamker, F.H. (2023). Exploring the Role of Feedback Inhibition for the Robustness Against Corruptions on Event-Based Data. In: Iliadis, L., Papaleonidas, A., Angelov, P., Jayne, C. (eds) Artificial Neural Networks and Machine Learning – ICANN 2023. ICANN 2023. Lecture Notes in Computer Science, vol 14261. Springer, Cham.' 


doi-Link: [https://doi.org/10.1007/978-3-031-44198-1_17](https://doi.org/10.1007/978-3-031-44198-1_17)

<p></p>

[Python code on Github](https://github.com/hamkerlab/Larisch2023_EventBasedSNN)

