---
title: "Sensory coding and contrast invariance emerge from the control of plastic inhibition over emergent selectivity"
description: 'Paper about the influence of inhibitory plasticity on the development of a V1 L4 SNN.'
date: 2021-11-29
---

### Abstract

Visual stimuli are represented by a highly efficient code in the primary visual cortex, but the development of this code is still unclear. Two distinct factors control coding efficiency: Representational efficiency, which is determined by neuronal tuning diversity, and metabolic efficiency, which is influenced by neuronal gain. How these determinants of coding efficiency are shaped during development, supported by excitatory and inhibitory plasticity, is only partially understood. We investigate a fully plastic spiking network of the primary visual cortex, building on phenomenological plasticity rules. Our results suggest that inhibitory plasticity is key to the emergence of tuning diversity and accurate input encoding. We show that inhibitory feedback (random and specific) increases the metabolic efficiency by implementing a gain control mechanism. Interestingly, this led to the spontaneous emergence of contrast-invariant tuning curves. Our findings highlight that (1) interneuron plasticity is key to the development of tuning diversity and (2) that efficient sensory representations are an emergent property of the resulting network.

Paper is published in PLoS Comput. Biol.

Please cite this work as:

Larisch,R., Gönner, L., Teichmann, M., Hamker, F. H. (2021). "Sensory coding and contrast invariance emerge from the control of plastic inhibition over emergent selectivity." <i>PLoS Comput. Biol.</i>

doi-Link: [https://doi.org/10.1371/journal.pcbi.1009566](https://doi.org/10.1371/journal.pcbi.1009566)

<p></p>

[Download paper here](https://journals.plos.org/ploscompbiol/article/file?id=10.1371/journal.pcbi.1009566&type=printable)

<p></p>

[Download a bioRxiv pre-print here ](https://www.biorxiv.org/content/10.1101/2020.04.07.029157v3.full.pdf)

<p></p>

[Python code on Github](https://github.com/hamkerlab/Larisch2021_PLOSComBio)

