---
title: "A Neural Spiking Approach Compared to Deep Feedforward Networks on Stepwise Pixel Erasement"
description: 'Contribution to the ICANN 2018 conference.'
date: 2018-09-28
---

### Abstract

In real world scenarios, objects are often partially occluded. This requires a robustness for object recognition against these perturbations. Convolutional networks have shown good performances in classification tasks. The learned convolutional filters seem similar to receptive fields of simple cells found in the primary visual cortex. Alternatively, spiking neural networks are more biological plausible. We developed a two layer spiking network, trained on natural scenes with a biologically plausible learning rule. It is compared to two deep convolutional neural networks using a classification task of stepwise pixel erasement on MNIST. In comparison to these networks the spiking approach achieves good accuracy and robustness.

This work was published in Artificial Neural Networks and Machine Learning - ICANN 2018. - Cham : Springer International Publishing. 253-262.

Please cite this work as:


'Larisch, R., Teichmann, M., Hamker, F.H. (2018). "A Neural Spiking Approach Compared to Deep Feedforward Networks on Stepwise Pixel Erasement. " <i>Artificial Neural Networks and Machine Learning - ICANN 2018. - Cham : Springer International Publishing. 253-262.</i>'

doi-Link: [http://dx.doi.org/10.1007/978-3-030-01418-6_25](http://dx.doi.org/10.1007/978-3-030-01418-6_25)

<p></p>

[Download an arXive pre-print here](https://arxiv.org/pdf/1912.03201)




